Global:
  algorithm: CRNN
  use_gpu: true
  epoch_num: 30
  log_smooth_window: 20
  print_batch_step: 100
  save_model_dir: output/rec_CRNN_aug_341
  save_epoch_step: 1
  eval_batch_step: 1800
  train_batch_size_per_card: 192
  test_batch_size_per_card: 64
  image_shape: [3, 32, 256]
  max_text_length: 64
  character_type: ch
  loss_type: ctc
  reader_yml: ./configs/rec/rec_icdar15_reader.yml
  pretrain_weights: /home/aistudio/work/PaddleOCR/output/rec_CRNN_aug_341/latest
  checkpoints: 
  save_inference_dir: /home/aistudio/work/test
  character_dict_path: /home/aistudio/work/dict.txt
  
Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_resnet_vd,ResNet
  layers: 34
 
Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: rnn
  SeqRNN:
    hidden_size: 256
    
Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.00001
  beta1: 0.9
  beta2: 0.999
